### ISSUE TITLE
@Stepwise doesn't work

### ISSUE THREAD

**Issue by johnroach** [saucelabs-sample-test-frameworks/Groovy-Geb-Spock-Selenium#3]
Hi,

I noticed something, when we create a test using `@Stepwise` the first feature test will pass but the second won't. Why is that?

**Comment by ndmanvar** [comment]
Hi John,

I will take a look at get back to you.
Author of this test framework is no longer with our company, so I will have to do some learning / experimenting first (:

-Neil

**Comment by johnroach** [comment]
I think I have a solution. I will see if I can create a pull request tonight.

**Comment by johnroach** [comment]
I created a pul request #4 that needs refactoring and more testing. But that is the general idea I was thinking about.

**Comment by johnroach** [comment]
@ndmanvar if you want we can do a in person code review and discuss. I am willing to help out and do testing.

**Comment by ndmanvar** [comment]
@JohnRoach That sounds great! Can you email me at neil@saucelabs.com and we can coordinate a day and time? Appreciate the help (:

**Comment by johnroach** [comment]
@ndmanvar created a new pull request after our talk #5 tell me what you think.

**Comment by johnroach** [comment]
I think we can close this since it got merged.
